name: "Ping someone in the comment"

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  main:
    name: Ping someone in the comment section of PR
    runs-on: ubuntu-latest
    steps:
      - uses: schoi-godaddy/ping-reviewer-aksion@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          who-to-ping: "schoi-godaddy"
